# Generated by Django 3.1.1 on 2021-03-24 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210324_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
